springdoc:
  version: v1.0.0
  api-docs:
    path: /api-docs/json
  swagger-ui:
    path: /api-docs

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  OAuth2:
    google:
      url: https://accounts.google.com/o/oauth2/v2/auth
      client-id: 555871325858-vg3s040vuv5drcf4fl2q20tnda2p2tst.apps.googleusercontent.com
      callback-url: http://localhost:8080/signin/social/google/form/callback
      client-secret: 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
      scope: https://www.googleapis.com/auth/userinfo.email

cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}
    s3:
      bucket: wetube-video
      dir: /videos
    region:
      static: ap-northeast-2
    stack:
      auto: false

jwt:
  token-issuer: wetube
  token-secret-key: SECRET__KEY